/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 27-jun.-2023 2:35:02 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */
/*
	Script for create the database of Microservice Users with name of cinepacho_dbusers
*/
DROP DATABASE IF EXISTS cinepacho_dbusers;
CREATE DATABASE IF NOT EXISTS  cinepacho_dbusers;

USE cinepacho_dbusers;

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS Clients CASCADE
;

DROP TABLE IF EXISTS Members CASCADE
;

DROP TABLE IF EXISTS Roles CASCADE
;

DROP TABLE IF EXISTS Users CASCADE
;

/* Create Tables */

CREATE TABLE Clients
(
	id BIGINT NOT NULL AUTO_INCREMENT,
	number_document VARCHAR(20) NOT NULL,
	rating_cinepacho DOUBLE(3,2) NULL,
	points INT NOT NULL DEFAULT 0,
	CONSTRAINT PK_Client PRIMARY KEY (id ASC)
)
COMMENT = 'Table of client in system'

;

CREATE TABLE Members
(
	id BIGINT NOT NULL AUTO_INCREMENT,
	number_document VARCHAR(20) NOT NULL,
	code_employee VARCHAR(20) NOT NULL,
	multiplex VARCHAR(80) NULL,
	salary INT NOT NULL,
	date_contract DATE NOT NULL,
	password VARCHAR(255) NOT NULL,
	CONSTRAINT PK_Members PRIMARY KEY (id ASC)
)
COMMENT = 'Table containt the employets in system, remember the 3 jobs, Admin, admMultiplex y empleado'

;

CREATE TABLE Roles
(
	id BIGINT NOT NULL AUTO_INCREMENT,
	description VARCHAR(255) NULL,
	name VARCHAR(255) NULL,
	CONSTRAINT PK_Role PRIMARY KEY (id ASC)
)
COMMENT = 'Table containt roles of users in system'

;

CREATE TABLE Users
(
	id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id generic of user',
	number_document VARCHAR(20) NOT NULL COMMENT 'Cedula of user',
	name VARCHAR(255) NOT NULL COMMENT 'name of user',
	date_birth DATE NOT NULL COMMENT 'date of born user',
	phone VARCHAR(10) NOT NULL,
	email VARCHAR(255) NOT NULL,
	id_role BIGINT NOT NULL COMMENT 'id generic and relational with role of user.',
	CONSTRAINT PK_User PRIMARY KEY (id ASC)
)
COMMENT = 'In this table containt the users of service Cine Pacho'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Clients 
 ADD CONSTRAINT UNIQUE_Number_Document UNIQUE (number_document ASC)
;

ALTER TABLE Clients 
 ADD CONSTRAINT CK_Rating CHECK (rating_cinepacho > 0)
;

ALTER TABLE Clients 
 ADD CONSTRAINT CK_Points CHECK (points >= 0)
;

ALTER TABLE Clients 
 ADD INDEX IXFK_Client_Users (number_document ASC)
;

ALTER TABLE Members 
 ADD CONSTRAINT UNIQUE_Number_Document UNIQUE (number_document ASC)
;

ALTER TABLE Members 
 ADD CONSTRAINT UNIQUE_Code_employee UNIQUE (code_employee ASC)
;

ALTER TABLE Members 
 ADD CONSTRAINT CK_Salary CHECK (salary > 0)
;

ALTER TABLE Members 
 ADD CONSTRAINT CK_Multiplex CHECK (multiplex in ('TITAN','UNICENTRO','PLAZA CENTRAL','GRAN ESTACION','EMBAJADOR', 'LAS AMERICAS'))
;

ALTER TABLE Members 
 ADD INDEX IXFK_Members_Users (number_document ASC)
;

ALTER TABLE Users 
 ADD CONSTRAINT UNIQUE_Number_Document UNIQUE (number_document ASC)
;

ALTER TABLE Users 
 ADD CONSTRAINT UNIQUE_Email UNIQUE (email ASC)
;

ALTER TABLE Users 
 ADD INDEX IXFK_Users_Roles (id_role ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Clients 
 ADD CONSTRAINT FK_Client_Users
	FOREIGN KEY (number_document) REFERENCES Users (number_document) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Members 
 ADD CONSTRAINT FK_Members_Users
	FOREIGN KEY (number_document) REFERENCES Users (number_document) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Users 
 ADD CONSTRAINT FK_Users_Roles
	FOREIGN KEY (id_role) REFERENCES Roles (id) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 